In [2]:
import pandas as pd
import os

In [3]:
folder = "C:\\Users\\Hrugved\\OneDrive\\Desktop\\DAY1\\data\\raw"


for file in sorted(os.listdir(folder)):
    
    if file.endswith(".csv"):
        
        df = pd.read_csv(os.path.join(folder,file))

        print("="*70)
        print(file)

        print("\nShape:")
        print(df.shape)

        print("\nDtypes:")
        print(df.dtypes)

        print("\nHead:")
        display(df.head())

======================================================================
01_fund_master.csv

Shape:
(40, 15)

Dtypes:
amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

Head:

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

======================================================================
02_nav_history.csv

Shape:
(46000, 3)

Dtypes:
amfi_code      int64
date             str
nav          float64
dtype: object

Head:

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

======================================================================
03_aum_by_fund_house.csv

Shape:
(90, 5)

Dtypes:
date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

Head:

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

======================================================================
04_monthly_sip_inflows.csv

Shape:
(48, 6)

Dtypes:
month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

Head:

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

======================================================================
05_category_inflows.csv

Shape:
(144, 3)

Dtypes:
month                   str
category                str
net_inflow_crore    float64
dtype: object

Head:

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

======================================================================
06_industry_folio_count.csv

Shape:
(21, 6)

Dtypes:
month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

Head:

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

======================================================================
07_scheme_performance.csv

Shape:
(40, 19)

Dtypes:
amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object

Head:

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

======================================================================
08_investor_transactions.csv

Shape:
(32778, 13)

Dtypes:
investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object

Head:

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

======================================================================
09_portfolio_holdings.csv

Shape:
(322, 8)

Dtypes:
amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object

Head:

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

======================================================================
10_benchmark_indices.csv

Shape:
(8050, 3)

Dtypes:
date               str
index_name         str
close_value    float64
dtype: object

Head:

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

======================================================================
Axis_Bluechip.csv

Shape:
(3569, 2)

Dtypes:
date        str
nav     float64
dtype: object

Head:

         date        nav
0  05-06-2026  6168.4755
1  04-06-2026  6160.9434
2  03-06-2026  6159.9626
3  02-06-2026  6158.9665
4  01-06-2026  6156.7532

======================================================================
ICICI_Bluechip.csv

Shape:
(3311, 2)

Dtypes:
date        str
nav     float64
dtype: object

Head:

         date       nav
0  05-06-2026  103.8102
1  04-06-2026  103.6421
2  03-06-2026  103.4809
3  02-06-2026  103.5959
4  01-06-2026  103.0948

======================================================================
Kotak_Bluechip.csv

Shape:
(3305, 2)

Dtypes:
date        str
nav     float64
dtype: object

Head:

         date       nav
0  05-06-2026  246.0878
1  04-06-2026  246.0784
2  03-06-2026  245.6593
3  02-06-2026  246.8566
4  01-06-2026  246.9814

======================================================================
Nippon_Large_Cap.csv

Shape:
(3302, 2)

Dtypes:
date        str
nav     float64
dtype: object

Head:

         date      nav
0  05-06-2026  97.2456
1  04-06-2026  97.2621
2  03-06-2026  97.2167
3  02-06-2026  97.4783
4  01-06-2026  97.1944

======================================================================
SBI_Bluechip.csv

Shape:
(3240, 2)

Dtypes:
date        str
nav     float64
dtype: object

Head:

         date       nav
0  05-06-2026  105.1070
1  04-06-2026  104.8095
2  03-06-2026  104.7496
3  02-06-2026  104.7663
4  01-06-2026  104.7025

======================================================================
hdfc_top100_nav.csv

Shape:
(3095, 2)

Dtypes:
date        str
nav     float64
dtype: object

Head:

         date       nav
0  05-06-2026  194.7547
1  04-06-2026  194.5220
2  03-06-2026  194.0810
3  02-06-2026  193.1295
4  01-06-2026  192.3195

In [4]:
for file in sorted(os.listdir(folder)):
    
    if file.endswith(".csv"):
        
        df = pd.read_csv(os.path.join(folder,file))

        print(file)

        print("Missing Values")
        print(df.isnull().sum())

        print("\nDuplicates")
        print(df.duplicated().sum())

01_fund_master.csv
Missing Values
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

Duplicates
0
02_nav_history.csv
Missing Values
amfi_code    0
date         0
nav          0
dtype: int64

Duplicates
0
03_aum_by_fund_house.csv
Missing Values
date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

Duplicates
0
04_monthly_sip_inflows.csv
Missing Values
month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

Duplicates
0
05_category_inflows.csv
Missing Values
month               0
category            0
net_inflow_crore    0
dtype: int64

Duplicates
0
06_industry_folio_count.csv
Missing Values
month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

Duplicates
0
07_scheme_performance.csv
Missing Values
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

Duplicates
0
08_investor_transactions.csv
Missing Values
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

Duplicates
0
09_portfolio_holdings.csv
Missing Values
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

Duplicates
0
10_benchmark_indices.csv
Missing Values
date           0
index_name     0
close_value    0
dtype: int64

Duplicates
0
Axis_Bluechip.csv
Missing Values
date    0
nav     0
dtype: int64

Duplicates
0
ICICI_Bluechip.csv
Missing Values
date    0
nav     0
dtype: int64

Duplicates
0
Kotak_Bluechip.csv
Missing Values
date    0
nav     0
dtype: int64

Duplicates
0
Nippon_Large_Cap.csv
Missing Values
date    0
nav     0
dtype: int64

Duplicates
0
SBI_Bluechip.csv
Missing Values
date    0
nav     0
dtype: int64

Duplicates
0
hdfc_top100_nav.csv
Missing Values
date    0
nav     0
dtype: int64

Duplicates
0

In [5]:
sip = pd.read_csv("C:\\Users\\Hrugved\\OneDrive\\Desktop\\DAY1\\data\\raw\\04_monthly_sip_inflows.csv")
sip[sip["yoy_growth_pct"].isnull()]

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN
5,2022-06,12276,5.60,7.50,5.18,NaN
6,2022-07,12140,5.65,9.21,5.25,NaN
7,2022-08,12694,5.71,8.90,5.31,NaN
8,2022-09,12976,5.80,9.40,5.41,NaN
9,2022-10,13040,5.93,9.52,5.55,NaN
10,2022-11,13306,6.00,8.80,5.62,NaN
11,2022-12,13573,6.05,7.60,5.70,NaN

### found missing values in 4th excel sheet ie in monthly sip inflows csv, however the missing values were in yoy_growth_percentage the early rows were NULL as earlier entries dont have previous months entries so pct cant be calculated therefore the dataset provided is neat.
### now moving onto exploring fund master csv

In [6]:
fund_master = pd.read_csv("C:\\Users\\Hrugved\\OneDrive\\Desktop\\DAY1\\data\\raw\\01_fund_master.csv")
fund_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 9.9 KB

In [7]:
fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [8]:
print("Unique Fund Houses:", fund_master["fund_house"].nunique())
print("Unique Categories:", fund_master["category"].nunique())
print("Unique Sub Categories:", fund_master["sub_category"].nunique())
print("Unique Risk Categories:", fund_master["risk_category"].nunique())

Unique Fund Houses: 10
Unique Categories: 2
Unique Sub Categories: 12
Unique Risk Categories: 5

### AMFI code is a ID of a mutual fund scheme. It acts as a reference for linking different mutual funds information across databases.

In [9]:
nav_history = pd.read_csv("data/raw/02_nav_history.csv")

In [10]:
nav_history.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.5 MB

In [11]:
nav_history.columns.tolist()

['amfi_code', 'date', 'nav']

In [12]:
master_codes = set(fund_master["amfi_code"])
nav_codes = set(nav_history["amfi_code"])
missing_codes = master_codes - nav_codes
print("AMFI codes in fund_master but not in nav_history:", missing_codes)

AMFI codes in fund_master but not in nav_history: set()

### All AMFI codes in nav history were found hence there are no missing nav, hence there is a strong consistency in both the datasets ie 01 & 02

### DAY 1 DATASET QUALITY SUMMARY

All the datasets were succesfully added, 10 datasets were in total. After thorough exploration and analysis it was found there were no duplicate records, only 12 missing values in SIP INFLOW dataset which were further recognised and the issue was solved in the above comments/code. These missing values were in the yoy_growth pct that could not be calculated as the formula requires previous year data which wasnt provided as they were earlier records. Furhtermore all AMFI code were validated by comparing codes in 02 to 01 no missing amfi codes were found. In conclusion DAY 1 task was successfully completed.